baseURL: https://appscode.com/blog/
languageCode: en-us
title: Blog | AppsCode
assetDir: static
googleAnalytics: UA-62096468-4
taxonomies:
  tag: tags
  author: authors
disableKinds:
- taxonomyTerm
enableEmoji: true
params:
  basePath: /blog/
  domain_appscode: https://appscode.com
  domain_kubedb: https://kubedb.com
  domain_kubevault: https://kubevault.com
  domain_kubeci: https://kube.ci
  domain_kubeshield: https://kubeshield.com
  domain_bytebuilders: https://appscode.com
  domain_accounts: https://accounts.appscode.com
  domain_marketplace: https://marketplace.appscode.com
  blog_url: https://appscode.com/blog
  slack_url: https://slack.appscode.com
  twitter_url: https://x.com/AppsCodeHQ
  facebook_url: https://www.facebook.com/appscode
  youtube_url: https://www.youtube.com/c/AppsCodeInc
  contact_email: support@appscode.com
  contact_phone: +1(650)241-8486
  domain_kubeform: https://kubeform.com
  github_url: https://github.com/appscode
  domain_pharmer: https://pharmer.dev
  domain_stash: https://stash.run
  comments:
    enable: true
    giscus:
      repo: bytebuilders/community
      repoId: R_kgDOG-h6rw
      category: Blog
      categoryId: DIC_kwDOG-h6r84COCFp
      map: title
  search_api_key: 8fd610038d901dd16a111e6f1568343bb969b084a1952dafdcb1545fd8c35e96
  domain_configsyncer: https://config-syncer.com
  domain_kubestash: https://kubestash.com
  domain_voyagermesh: https://voyagermesh.com
  domain_guard: https://kubeguard.dev
  docs_url: https://appscode.com/docs
  learn_url: https://appscode.com/learn
  domain_gateway: https://gateway.voyagermesh.com
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
  - HTML
  - JSON
