baseURL: https://blog.byte.builders/
languageCode: en-us
title: ByteBuilders Blog
assetDir: static
googleAnalytics: UA-62096468-4
taxonomies:
  tag: tags
  author: authors
disableKinds:
- taxonomyTerm
params:
  domain_appscode: https://appscode-v3-hugo.web.app
  domain_kubedb: https://kubedb-v2-hugo.web.app
  domain_kubevault: https://kubevault-v1-hugo.web.app
  domain_kubeci: https://kubeci-v1-hugo.web.app
  domain_kubeshield: https://kubeshield-v1-hugo.web.app
  domain_bytebuilders: https://byte.builders
  domain_marketplace: https://marketplace.byte.builders
  search_engine_ID: 015199383701854252104:jccvu4eiulw
  search_api_key: _replace_
  blog_url: https://blog.byte.builders
  slack_url: https://slack.appscode.com
  twitter_url: https://twitter.com/AppsCodeHQ
  facebook_url: https://www.facebook.com/appscode
  youtube_url: https://www.youtube.com/c/AppsCodeInc
  contact_email: support@appscode.com
  contact_phone: +1(650)241-8486
  domain_kubeform: https://kubeform-v1-hugo.web.app
  github_url: https://github.com/appscode
  domain_pharmer: https://pharmer-v1-hugo.web.app
  domain_stash: https://stashed-v1-hugo.web.app
markup:
  goldmark:
    renderer:
      unsafe: true
