baseURL: https://byte.builders/blog/
languageCode: en-us
title: Blog | ByteBuilders
assetDir: static
googleAnalytics: UA-62096468-4
taxonomies:
  tag: tags
  author: authors
disableKinds:
- taxonomyTerm
enableEmoji: true
params:
  basePath: /blog/
  domain_appscode: https://appscode.com
  domain_kubedb: https://kubedb.com
  domain_kubevault: https://kubevault.com
  domain_kubeci: https://kube.ci
  domain_kubeshield: https://kubeshield.com
  domain_bytebuilders: https://byte.builders
  domain_accounts: https://accounts.byte.builders
  domain_marketplace: https://marketplace.byte.builders
  blog_url: https://blog.byte.builders
  slack_url: https://slack.appscode.com
  twitter_url: https://twitter.com/AppsCodeHQ
  facebook_url: https://www.facebook.com/appscode
  youtube_url: https://www.youtube.com/c/AppsCodeInc
  contact_email: support@appscode.com
  contact_phone: +1(650)241-8486
  domain_kubeform: https://kubeform.com
  github_url: https://github.com/appscode
  domain_pharmer: https://pharmer.dev
  domain_stash: https://stash.run
  comments:
    enable: true
    giscus:
      repo: bytebuilders/community
      repoId: R_kgDOG-h6rw
      category: Blog
      categoryId: DIC_kwDOG-h6r84COCFp
      map: title
  search_api_key: _replace_
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
  - HTML
  - JSON
